# feign 配置
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true

# hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
  shareSecurityContext: true

# 请求处理的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

# OAuth2配置
security:
  oauth2:
    client:
      client-id: user
      client-secret: user
      scope: all
      grant-type: client_credentials
      userAuthorizationUri: http://localhost:3000/oauth/authorize
      access-token-uri: http://localhost:3000/oauth/token
    resource:
      token-info-uri: http://localhost:3000/oauth/check_token
    authorization:
      check-token-access: http://localhost:3000/oauth/check_token

# 直接放行URL
ignore:
  urls:
    - /users/info/*